example-web:
  container_name: example-web
  build: .
  command: bash -c "java -jar target/dwexample.jar server config.yml"
  ports:
    - 8080:8080
    - 8081:8081

example-db:
  container_name: example-db
  image: postgres:9.6.2
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    PGDATA: /var/lib/postgresql/data/pgdata